//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredTo
    {
        public string ID { get; set; }
        public int TaskNumber { get; set; }
        public string Recommendation { get; set; }
        public string Rating { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
