//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyHelpMe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Task = new HashSet<Task>();
        }
    
        public int RequestCode { get; set; }
        public string RequestName { get; set; }
        public Nullable<bool> PrivateRequest { get; set; }
        public string Link { get; set; }
        public string ID { get; set; }
        public Nullable<int> StreetCode { get; set; }
        public Nullable<int> CityCode { get; set; }
        public string RequestStatus { get; set; }
    
        public virtual Street Street { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Task { get; set; }
    }
}
